//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOAffinities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AffinitiesEntities : DbContext
    {
        public AffinitiesEntities()
            : base("name=AffinitiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_HIERARQUIA> TB_HIERARQUIA { get; set; }
        public DbSet<TB_LAYOUT_ARQUIVO> TB_LAYOUT_ARQUIVO { get; set; }
        public DbSet<TB_LAYOUT_ARQUIVO_DETALHE> TB_LAYOUT_ARQUIVO_DETALHE { get; set; }
        public DbSet<TB_LISTA> TB_LISTA { get; set; }
        public DbSet<TB_LISTA_DETALHE> TB_LISTA_DETALHE { get; set; }
        public DbSet<TB_OBRIGATORIO> TB_OBRIGATORIO { get; set; }
        public DbSet<TB_PRODUTO> TB_PRODUTO { get; set; }
        public DbSet<TB_TIPO> TB_TIPO { get; set; }
        public DbSet<TB_VALIDACAO> TB_VALIDACAO { get; set; }
    }
}
