//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOAffinities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LISTA_DETALHE
    {
        public int ID_LISTA_DETALHE { get; set; }
        public int ID_LISTA { get; set; }
        public string DES_VALOR { get; set; }
    
        public virtual TB_LISTA TB_LISTA { get; set; }
    }
}
