//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOAffinities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LAYOUT_ARQUIVO
    {
        public TB_LAYOUT_ARQUIVO()
        {
            this.TB_PRODUTO = new HashSet<TB_PRODUTO>();
        }
    
        public int ID_LAYOUT_ARQUIVO { get; set; }
        public string NOM_LAYOUT_ARQUIVO { get; set; }
    
        public virtual ICollection<TB_PRODUTO> TB_PRODUTO { get; set; }
    }
}
