//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOAffinities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUTO
    {
        public int COD_PRODUTO { get; set; }
        public string NOM_PRODUTO { get; set; }
        public int ID_LAYOUT_ARQUIVO { get; set; }
    
        public virtual TB_LAYOUT_ARQUIVO TB_LAYOUT_ARQUIVO { get; set; }
    }
}
