//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOAffinities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPO
    {
        public TB_TIPO()
        {
            this.TB_LAYOUT_ARQUIVO_DETALHE = new HashSet<TB_LAYOUT_ARQUIVO_DETALHE>();
        }
    
        public int ID_TIPO { get; set; }
        public string NOM_TIPO { get; set; }
    
        public virtual ICollection<TB_LAYOUT_ARQUIVO_DETALHE> TB_LAYOUT_ARQUIVO_DETALHE { get; set; }
    }
}
